name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Rebuild
      run: cd doc-src && make github
    - uses: jakejarvis/s3-sync-action@v0.5.1
      name: Upload
      with:
        args: --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'doc-src/_build/html'
        DEST_DIR: 'itpp.dev/sync/'
    - uses: matheusalbino/git-commit@v1.0.1
      name: Commit updates
      with:
        user-name: Marc Demo (from Github Actions)
        user-email: i18n-bot@it-projects.info
        message: |
          :alien: recompile docs
          
          Sent from Github Actions (see .github/workflows/main.yml )
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}

